# Build and push a container
# Based on Boulder's release.yml
name: Build Release
on:
  push:
    tags:
      - release-*
jobs:
  push-release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build container
        run: podman build . -f Containerfile -t "ghcr.io/mcpherrinm/image-signing-test:$REF"
        env:
          REF: ${{ github.ref_name }}

      - name: Login to ghcr.io
        run: printenv GITHUB_TOKEN | podman login ghcr.io --username "$USER" --password-stdin
        env:
          USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Template OIDC
        run: envsubst < containers-sigstore-signing-params.yaml > "$RUNNER_TEMP/sign.yaml"

      - name: Push container
        run: podman push --sign-by-sigstore "$RUNNER_TEMP/sign.yaml" "ghcr.io/mcpherrinm/image-signing-test:$REF"
        env:
          REF: ${{ github.ref_name }}
